# This is a basic workflow to help you get started with Actions

name: CI
runs-on: self-hosted
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install venv
        run: |
          echo Hello, world!
          python --version
          python -m venv ./venv
          Invoke-Expression ("venv/Scripts/activate.ps1")
          pip install mypy flake8

      - name: type-test-job
        run: |
          ls
          echo Start mypy...
          mypy --ignore-missing-imports ./*.py

      - name: lint-test-job   
        run: |
          echo "Linting code... This will take about 10 seconds."
          flake8 ./*.py
